### ISSUE TITLE
Open API

### ISSUE THREAD

**Issue by hinell** [ignorabilis/any-api#1]
You basicaclly reinwented the [OpenAPI](https://www.openapis.org/)

**Comment by ignorabilis** [comment]
Thanks, I've been wondering if OpenAPI already does the thing that I need. Unfortunately, it doesn't, as the problem I'm trying to solve is a bit different. Though to be super honest looking at OpenAPI would be beneficial at that point of the development.

Btw how did you stumble upon my profile/repo - I wouldn't imagine a repo with no stars, written in Clojure a week or two ago ranks highly in Google search... Or any search for that matter. And you're not a Clojure dev, etc.

**Comment by hinell** [comment]
Just came across.

**Comment by hinell** [comment]
Just came across your [post over here](https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9?permalink_comment_id=4608217#gistcomment-4608217).
